"""
A shopping mall is waiting for its inaugural function. With an intention to attract the crowd, they are in plan to host a lucky-pick facility. 
The idea is to develop a lucky-pick device that anybody who comes to the mall can use by entering any six digit number. 
Their luck depends upon the number they enter. The lucky person gets the gift displayed in the lucky-pick device. 


 Now, as an Engineer who works for this mall, you're in-charge of programming this device.

Here are the technical details that may be helpful for you: 
1. STRATEGY IN PICKING THE LUCKY PERSON 
1.1 The number received from the user should be made to a single digit number by adding the digits of that number.
 Example: If user enters 123456, adding individual digits gives 1+2+3+4+5+6=21, from 21 again adding its digits gives 2+1=3. 
 So the desired single digit number in this example is 3. 
1.2 The resultant value (in this example: 3) should match with any of the 5 single digit random numbers generated by the device.

(Say if the random numbers generated are 1,9,5,7,3 then since the resultant 3 is coinciding with the random numbers list, the person gets a gift. 
 But if the numbers generated were 9,6,1,8,4 then as resultant 3 is not in this list of numbers, the person will receive nothing) 
1.3 The device should generate new round of random numbers for every single lucky-pick. 


2. GIFT SELECTION STRATEGY 
2.1 We have been given with a list of items which they are planning to gift. 
The list includes spiderman toy, barbie doll, Suzuki Access scooty, Royal Enfield bullet, dhothi, T-shirt, saree, churidhar, cosmetics, dinner set, parker pen, Tata Tigor car and Amazon gift card. 
2.1 Gift for lucky person is picked in random by the device itself. 
2.3 Costly gifts like Suzuki Access scooty, Royal Enfield bullet and Tata Tigor car are only available in 1 unit each.
 So, these gifts if once given to a lucky drawer then it should not be repeated for another new lucky drawer.

"""


import random as r

#to get single digit
def getsingledigit(n):
    sum=0;
    while(n>0):
        sum+=n%10;
        n//=10;
    return sum;

#to get random 5 digit list 
def randintlist(rlist):
    i=0;
    while(i<5):
        rlist.append(r.randint(1,9));
        i+=1;
    return rlist;

#to check luck
def tocheckluck(gifts, rlist, n):
    if n in rlist:
        luckyRandnumber=r.randint(0,12);
        for index, key in enumerate(gifts):
            if(index==luckyRandnumber and gifts.get(key)>0):
                temp=gifts[key];
                temp-=1;
                gifts[key]=temp;
                return key;
    else:
        return False;
    return False;

chk='y';
gifts={
    "spiderman toy":5,
    "barbie doll":5,
    "Suzuki Access scooty":1,
    "Royal Enfield bullet":1,
    "dhothi":5,
    "T-shirt":5,
    "saree":5,
    "churidhar":5,
    "cosmetics":5,
    "dinner set":5,
    "parker pen":5,
    "Tata Tigor car":1,
    "Amazon gift card":20
    };

print("------------------------------------------------------------------");

#for number of users
while(chk=='y'):
    #Each time initially list should be empty
    rlist=[];
    #for taking input
    n=int(input("Enter the Number"));
    
    #looping until to get single digit
    while(n>9):
        n=getsingledigit(n);
    #funtioncall
    rlist=randintlist(rlist);
    reward=tocheckluck(gifts, rlist, n);
    if(reward!=False):
        print("Hurray..!!\N{grinning face}\N{grinning face} *You got {} \N{smiling face with sunglasses}*".format(reward));
    else:
        print("Ooops..!!\N{loudly crying face}\N{loudly crying face} *Better luck for next time\N{slightly smiling face}*");
    print("------------------------------------------------------------------");
    chk=input("Want to continue for next lucky draw....??y/n").lower();
